blogpost/urls.py
from django.urls import path

from blogpost.apps import BlogPostConfig
from blogpost.views import (BlogPostCreateView, BlogPostDetailView, BlogPostListView,
                            BlogPostUpdateView, BlogPostDeleteView, toggle_activity)

app_name = BlogPostConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogPostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name="toggle_activity"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace= 'catalog')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

blogpost/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание', **NULLABLE)
    image = models.ImageField(upload_to='blogpost/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания', **NULLABLE)
    is_active = models.BooleanField(default=True)
    number_of_views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    slug = models.CharField(max_length=200, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return f"{self.title} {self.slug} {self.content}"

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blogpost/forms.py
from django.forms import ModelForm

from blogpost.models import BlogPost


class BlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        exclude = ("slug", "created_at", "number_of_views",)

blogpost/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from pytils.translit import slugify

from blogpost.forms import BlogPostForm
from blogpost.models import BlogPost


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    form_class = BlogPostForm
    success_url = reverse_lazy('blogpost:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogpost.add_blogpost'):
            return BlogPostForm
        raise PermissionDenied



class BlogPostListView(LoginRequiredMixin, ListView):
    model = BlogPost
    login_url = "/users/login/"
    redirect_field_name = "login"


    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_active=True)
        return queryset


class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    form_class = BlogPostForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogpost.change_blogpost'):
            return BlogPostForm
        raise PermissionDenied

    def get_success_url(self):
        return reverse('blogpost:view', args=[self.kwargs.get('pk')])




class BlogPostDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blogpost:list')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogpost.delete_blogpost'):
            return BlogPostForm
        raise PermissionDenied







def toggle_activity(request, pk):
    blogpost_item = get_object_or_404(BlogPost, pk=pk)
    if blogpost_item.is_active:
        blogpost_item.is_active = False
    else:
        blogpost_item.is_active = True
    blogpost_item.save()
    return redirect(reverse('blogpost:list'))

blogpost/templates/blogpost/blogpost_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Хотите удалить {{object.title }} ?</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-lg btn-outline-danger">
                                Подтвердить
                            </button>
                            <a type="submit" class="btn btn-lg btn-outline-primary"
                               href="{% url 'blogpost:list' %}">Отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blogpost_detail.html
{% extends 'catalog/home.html' %}
{% load my_foto%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h6 class="card-title">Статья: {{ object.title }} ({{ object.slug }})</h6>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <img src="{{ object.image|media_filter }}" height="120" class="img-thumbnail">
                        <li>- {{ object.content }}</li>
                        <li>- {{ object.created_at }}</li>
                        <li>- {{ object.slug }}</li>
                    </ul>
                    <div class="btn-group">
                        {% if perms.blogpost.change_blogpost and perms.blogpost.delete_blogpost %}
                        <a href="{% url 'blogpost:edit' object.pk %}"
                           class="btn btn-sm btn-outline-primary">Править</a>
                        <a href="{% url 'blogpost:delete' object.pk %}"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}
                        <a href="{% url 'blogpost:list' %}"
                           class="btn btn-sm btn-outline-success">Назад</a>
                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.number_of_views }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blogpost_form.html
{% extends 'catalog/home.html' %}
{% block content %}
{% load my_foto %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blogpost_list.html
{% extends 'catalog/home.html' %}
{% load my_foto %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <p>
            {% if perms.blogpost.add_blogpost %}
            <a href="{% url 'blogpost:create' %}" class="btn btn-primary my-2">Добавить статью</a>
            {% endif %}
        </p>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <img src="{{object.image | media_filter}}" height="99" class="img-thumbnail">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blogpost:view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-primary">Посмотреть</a>
                                {% if perms.blogpost.change_blogpost and perms.blogpost.delete_blogpost %}
                                <a href="{% url 'blogpost:edit' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-warning">Редактировать</a>
                                <a href="{% url 'blogpost:delete' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-danger">Удалить</a>
                                {% endif %}
                            </div>
                            {% if perms.blogpost.add_blogpost and perms.blogpost.change_blogpost and perms.blogpost.delete_blogpost %}
                            {% if object.is_active %}
                            <a class="btn btn-sm btn-warning"
                               href="{% url 'blogpost:toggle_activity' object.pk %}">Деактивировать</a>
                            {% else %}
                            <a class="btn btn-sm btn-success"
                               href="{% url 'blogpost:toggle_activity' object.pk %}">Активировать</a>
                            {% endif %}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}