catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ProductListView, ProductDetailView, ContactsCreateView, ProductCreateView, ProductUpdateView, \
    CategoryListView, CategoryDetailView
from catalog.apps import MainConfig

app_name = MainConfig.name





urlpatterns = [

    path('', ProductListView.as_view(), name='list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('catalog/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('contacts', ContactsCreateView.as_view(), name='contacts_list'),
    path('categoty', CategoryListView.as_view(), name='category_list'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),


]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace= 'catalog')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

catalog/models.py
from django.db import models
from pytils.translit import slugify

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Категория',
                             help_text='Введите категорию продукта')
    description = models.TextField(verbose_name='Описание', **NULLABLE,
                                   help_text='Введите описание категории продукта')
    slug = models.SlugField(max_length=100, db_index=True, verbose_name='URL', **NULLABLE)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return f'Категория: {self.title}'

    class Meta:

        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название продукта', help_text='Введите название продукта')
    description = models.TextField(verbose_name='Описание', help_text='Введите описание продукта')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE,
                              help_text='Введите фото продукта. если оно есть')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', related_name="products",
                                 help_text='Выберите категорию продукта')
    price = models.IntegerField(verbose_name='Цена', help_text='Введите цену продукта')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания релиза')

    number_of_views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)
    publication = models.BooleanField(default=False, verbose_name='Публикация')
    slug = models.SlugField(max_length=100, db_index=True, verbose_name='URL', **NULLABLE)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return f'Наименование: {self.name}, Категория: {self.category}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

        permissions = [
            ('unpublish_product', 'Unpublish a product'),
            ('change_product_description', 'Change the description of any product'),
            ('change_product_category', 'Change the category of any product'),
        ]

    def form_valid(self, form):
        pass


class Contacts(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя',
                                  help_text='Введите имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия', help_text='Введите фамилию')
    phone = models.CharField(max_length=100, verbose_name='Телефон', help_text='Введите телефон')
    message = models.CharField(max_length=100, verbose_name='Сообщение', **NULLABLE, help_text='Введите сообщение')
    email = models.EmailField(verbose_name='Электронная почта', **NULLABLE,
                              help_text='Введите адрес электронной почты')

    def __str__(self):
        return f'{self.first_name} {self.email}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Version(models.Model):
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE, related_name='versions',
                                help_text='Выберите продукт')
    version_number = models.PositiveIntegerField(verbose_name='Номер версии',
                                                 help_text='Введите номер версии продукта')
    version_name = models.CharField(max_length=150, verbose_name="Название версии",
                                    help_text='Введите название версии продукта')
    version_now = models.BooleanField(default=True, verbose_name="Признак текущей версии")

    def __str__(self):
        return f" {self.version_number} | {self.version_name} "

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django.forms import ModelForm, forms

from catalog.models import Product, Version, Category
from django.forms.fields import BooleanField
forbidden_words = ['казино',
                   'криптовалюта',
                   'крипта',
                   'биржа',
                   'дешево',
                   'бесплатно',
                   'обман',
                   'полиция',
                   'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ("number_of_views", "owner")

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for word in forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя использовать слова: {forbidden_words} !!!')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя использовать слова: {forbidden_words} !!!')
        return cleaned_data


class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ("category", "description", "publication")


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

    def clean_name(self):
        cleaned_data = self.cleaned_data['version_name']
        for word in forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Нельзя использовать слова: {forbidden_words}')
        return cleaned_data




class CategoryForm(StyleFormMixin,ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse_lazy


from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Contacts, Version, Category
from catalog.services import get_products_from_cache, get_categories_from_cache


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    login_url = "/users/login/"
    redirect_field_name = "login"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()
        return context_data

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'

    def get_queryset(self):
        return get_products_from_cache()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = self.get_queryset(*args, **kwargs)
        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(version_now=True)
            if active_versions:
                product.active_version = active_versions.last().version_name
            else:
                product.active_version = 'Нет активной версии'
        context_data['object_list'] = products
        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    login_url = "/users/login/"
    redirect_field_name = "login"
    template_name = 'catalog/product_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product = self.get_object()
        versions = Version.objects.filter(product=product)
        active_version = versions.filter(version_now=True).last()
        if active_version:
            product.active_version = active_version.version_name
        else:
            product.active_version = 'Нет активной версии'
        context_data['object'] = product
        context_data['version'] = product.active_version
        return context_data


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    login_url = "/users/login/"
    redirect_field_name = "login"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super(ProductUpdateView, self).form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('catalog.unpublish_product') and user.has_perm('catalog.change_product_description')
                and user.has_perm('catalog.change_product_category')):
            return ProductModeratorForm
        raise PermissionDenied


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category_list.html'

    def get_queryset(self):
        return get_categories_from_cache()


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    template_name = 'category/category_detail.html'

    def get(self, request, slug):
        category = Category.objects.all()
        products = Product.objects.filter(category__slug=slug)

        context = {
            'category': category,
            'products': products,
        }
        return render(request, 'catalog/category_detail.html', context)


class ContactsCreateView(CreateView):
    model = Contacts
    fields = ('first_name', 'last_name', 'phone', 'message', 'email')
    template_name = 'catalog/contacts_form.html'
    success_url = reverse_lazy('catalog:contacts_list')

catalog/templates/catalog/category_detail.html
{% extends 'catalog/home.html' %}
{% block content %}
{% load my_tags %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        {% if user.is_authenticated %}
        <p>
            <a href="{% url 'catalog:create' %}" class="btn btn-primary my-2">Добавить продукт</a>
        </p>
        {% else %}
        <p>
            <a class="btn btn-danger my-2">Просматривать,добавлять или редактировать могут только авторизованные
                пользователи </a>
        </p>
        {% endif %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
{% if products %}
   {% for object in products %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{object.image|media_filter}}" height="250" class="img">
                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p>Активная версия: {{ object.active_version }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:view' object.pk %}" role="button">Посмотреть</a>
                                {% if perms.catalog.unpublish_product and perms.catalog.change_product_description and perms.catalog.change_product_category or user == object.owner%}
                                    <a class="btn btn-warning" href="{% url 'catalog:edit' object.pk %}" role="button">Редактировать</a>
                                {% endif %}
                            </div>
                            <small class="text-body-secondary"></small>
                        </div>
                    </div>
                </div>
            </div>
   {% endfor %}
{% endif %}
                 </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">

<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
{% include 'catalog/inc_menu.html' %}
</header>

<main>

  <section class="py-2 text-center container">
    <div class="row py-lg-1">
      <div class="col-lg-4 col-md-6 mx-auto">
        <h1 class="fw-light">Магазин полезного ПО</h1>
        <p class="lead text-body-secondary">Разрабатываем по индивидуальному заказу любое программное обеспечение</p>
        <p>
          <a href="{% url 'catalog:list' %}" class="btn btn-primary my-2">На главную</a>
          <a href="{% url 'catalog:category_list' %}" class="btn btn-danger my-2">Каталог</a>
          <a href="{% url 'blogpost:list' %}" class="btn btn-success my-2">Статьи</a>
        </p>
      </div>
    </div>
  </section>

{% block content %}
{% endblock %}

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Москва 2024</p>

  </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

catalog/templates/catalog/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-4 row-cols-md-4 g-3">
            <div class="col-md-4 col-md-2 py-4">
                <h4>О нас</h4>
                <ul class="text-body-secondary">
                    <li><a class="text-white">Магазин полезного ПО</a></li>
                    <li><a class="text-white">ООО "Код"</a></li>
                    <li><a class="text-white"> ИНН 9999999999</a></li>
                    <li><a class="text-white">г. Москва, тел. 9999999999</a></li>
                </ul>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
<!--                <a href="{% url 'catalog:category_list' %}" class="btn btn-primary my-2">Каталог</a>-->

            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Навигация</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'catalog:list' %}" class="text-white">На главную</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                    <li><a href="{% url 'users:profile' %}" class="text-white">Редактирование профиля</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    {% endif %}
                    <li><a href="{% url 'blogpost:list' %}" class="text-white">Статьи</a></li>
                    <li><a href="{% url 'catalog:contacts_list' %}" class="text-white">Задайте вопрос</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                 stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                 viewBox="0 0 24 24">
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                <circle cx="12" cy="13" r="4"/>
            </svg>
            <strong>Поиск</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% block content %}
{% load my_tags %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        {% if user.is_authenticated %}
        <p>
            <a href="{% url 'catalog:create' %}" class="btn btn-primary my-2">Добавить продукт</a>
        </p>
        {% else %}
        <p>
            <a class="btn btn-danger my-2">Просматривать,добавлять или редактировать могут только авторизованные
                пользователи </a>
        </p>
        {% endif %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{object.image|media_filter}}" height="250" class="img">
                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p>Активная версия: {{ object.active_version }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:view' object.pk %}" role="button">Посмотреть</a>
                                {% if perms.catalog.unpublish_product and perms.catalog.change_product_description and perms.catalog.change_product_category or user == object.owner%}
                                    <a class="btn btn-warning" href="{% url 'catalog:edit' object.pk %}" role="button">Редактировать</a>
                                {% endif %}
                            </div>
                            <small class="text-body-secondary"></small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}